name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  id-token: write
  contents: read

env:
  GOEXPERIMENT: "jsonv2"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: stable
          cache: true
          cache-dependency-path: go.sum

      - name: Run go mod download
        run: go mod download

      - name: Check clock file
        run: ls -l ./clock

      - name: Test
        run: |
          make test
      - name: Upload coverage to Qlty
        uses: qltysh/qlty-action/coverage@v2
        with:
          oidc: true
          files: c.out
