name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  id-token: write
  contents: read

env:
  GO111MODULE: "on"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: latest
          cache: true
          cache-dependency-path: go.sum

      - name: Run go mod download
        run: go mod download

      - name: Check clock file
        run: ls -l ./clock

      - name: Test
        run: |
          go test -coverprofile=c.out ./config ./clock ./core ./middleware
      - name: Upload coverage to Qlty
        uses: qltysh/qlty-action/coverage@v2
        with:
          oidc: true
          files: c.out
